export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHORS_ERROR = 'LOAD_AUTHORS_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_ERROR = 'LOAD_COURSES_ERROR';
export const CREATE_COURSES_SUCCESS = 'CREATE_COURSES_SUCCESS';
export const CREATE_COURSES_ERROR = 'CREATE_COURSES_ERROR';
export const UPDATE_COURSES_SUCCESS = 'UPDATE_COURSES_SUCCESS';
export const UPDATE_COURSES_ERROR = 'UPDATE_COURSES_ERROR';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';
export const UPDATE_COURSE_IS_OPEN = 'UPDATE_COURSE_IS_OPEN';
export const UPDATE_COURSE_IS_CLOSED = 'UPDATE_COURSE_IS_CLOSED';

export const LOAD_OPEN_COURSES_SUCCESS = 'LOAD_OPEN_COURSES_SUCCESS';
export const LOAD_OPEN_COURSES_ERROR = 'LOAD_OPEN_COURSES_ERROR';
export const INTERNALLY_OPEN_COURSE_UPDATE_MSG = 'INTERNALLY_OPEN_COURSE_UPDATE_MSG';
export const INTERNALLY_OPEN_COURSE_UPDATE_SECS = 'INTERNALLY_OPEN_COURSE_UPDATE_SECS';
export const INTERNALLY_OPEN_COURSE_IS_UPDATING = 'INTERNALLY_OPEN_COURSE_IS_UPDATING';
export const UPDATED_OPEN_COURSE_SUCCESS = 'UPDATED_OPEN_COURSE_SUCCESS';
export const UPDATED_OPEN_COURSE_ERROR = 'UPDATED_OPEN_COURSE_ERROR';

export const OPEN_COURSE_FORM_SCREEN = 'OPEN_COURSE_FORM_SCREEN';
export const CLOSE_COURSE_FORM_SCREEN = 'CLOSE_COURSE_FORM_SCREEN';

export const OPEN_COURSE_IS_OPEN_SCREEN = 'OPEN_COURSE_IS_OPEN_SCREEN';
export const CLOSE_COURSE_IS_OPEN_SCREEN = 'CLOSE_COURSE_IS_OPEN_SCREEN';

export const UPDATE_COURSE_IS_OPEN_SUCCESS = 'UPDATE_COURSE_IS_OPEN_SUCCESS';
export const UPDATE_COURSE_IS_OPEN_NEW_SUCCESS = 'UPDATE_COURSE_IS_OPEN_NEW_SUCCESS';
export const UPDATE_COURSE_IS_OPEN_ERROR = 'UPDATE_COURSE_IS_OPEN_ERROR';

export const DELETE_COURSE_IS_OPEN_SUCCESS = 'DELETE_COURSE_IS_OPEN_SUCCESS';
export const DELETE_COURSE_IS_OPEN_ERROR = 'DELETE_COURSE_IS_OPEN_ERROR';

export const OPEN_LOGIN_SCREEN = 'OPEN_LOGIN_SCREEN';
export const CLOSE_LOGIN_SCREEN = 'CLOSE_LOGIN_SCREEN';

export const POST_AUTH_REDIRECT_PATH = 'POST_AUTH_REDIRECT_PATH';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const USER_LOGGED_OFF = 'USER_LOGGED_OFF';
export const USER_STILL_AUTHENTICATED = 'USER_STILL_AUTHENTICATED';

export const LOGIN_PAGE_INITIAL_ANIMATION = 'LOGIN_PAGE_INITIAL_ANIMATION';